[package]
name = "prerendering"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmedge-sdk = "0.4.0"
wasmedge-sys = "*"
anyhow = "1.0"

[build-dependencies]
wasmedge-sdk = "0.4.0"
wasmedge-sys = "*"
anyhow = "1.0"