test:
	#. ${HOME}/.wasmedge/env \
#		&& . ${HOME}/.cargo/env \
#		&& cargo run \
#			-vv \
#			--color=always \
#			--manifest-path \
#				./Cargo.toml \
#			-- \
#			--nocapture

	. ${HOME}/.wasmedge/env \
		&& . ${HOME}/.cargo/env \
		&& cargo test \
				-vv \
				--color=always \
				--manifest-path \
					./Cargo.toml \
			 \
			-- \
				--nocapture